name: nest-practice

services:
  postgres:
    image: postgres:15
    env_file: '.env'
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres | grep accepting']
      interval: 1s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    env_file: '.env'
    ports:
      - '${REDIS_PORT}:6379'
    restart: always
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 3
